### PR TITLE
Add functionality to seed database with dummy data. 

### PR DESCRIPTION
**Pull request by spraguejdev**
Instructions to test environment
- NPM install
- npm run dummyData
- npm run seed-db

### CODE REVIEW

**Review by bjlagman12 — APPROVED** [review]
I forked your repo and tried testing from my end. Everything looks good. Good Job! One thing I wasnt clear on was whats the difference with "dummyData" and "seed-db" shouldn't it be executed in one node file? @leightonchen thoughts??

**Comment by spraguejdev** [comment]
@brian, I simple wanted to separate the concerns. I feel like the dummy data script is different than inserting the data into mongo. I may be wrong though, and in hindsight, I want to change the name of the script to be clear. Thanks for the review!

**Comment by leightonchen** [comment]
@bjlagman12 @wizard-jS If it's a seeding script, I think it can be done all in 1 file. Separation of concerns is not an issue here, since you won't be using that fake dummy data or that seeding script anywhere else.

**Comment by spraguejdev** [comment]
@bjlagman12 @leightonchen I merged the dummyData.js file into db.js as suggested. Thanks for the feedback!

**Pull request merged**
